export const DECREASE_HEALTH = "DECREASE_HEALTH";
export const RESET_HEALTH = "RESET_HEALTH";
export const DECREASE_HEALTH_BY_AMOUNT = "DECREASE_HEALTH_BY_AMOUNT";
export const USE_HEALTH_POTION = "USE_HEALTH_POTION";
